/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistrationIndexRouteImport } from './routes/registration/index'
import { Route as OfficeIndexRouteImport } from './routes/office/index'
import { Route as BookingsIndexRouteImport } from './routes/bookings/index'
import { Route as BookIndexRouteImport } from './routes/book/index'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings/$bookingId'
import { Route as BookEqIdRouteImport } from './routes/book/$eqId'
import { Route as OfficeConfigurationIndexRouteImport } from './routes/office/configuration/index'
import { Route as ApiFileIndexRouteImport } from './routes/api/file/index'
import { Route as OfficeRegistrationViewIndexRouteImport } from './routes/office/registration/view/index'
import { Route as OfficeRegistrationEditIndexRouteImport } from './routes/office/registration/edit/index'
import { Route as OfficeEquipmentEditIndexRouteImport } from './routes/office/equipment/edit/index'
import { Route as OfficeBookingViewIndexRouteImport } from './routes/office/booking/view/index'
import { Route as OfficeRegistrationViewRegIdRouteImport } from './routes/office/registration/view/$regId'
import { Route as OfficeEquipmentEditEqIdRouteImport } from './routes/office/equipment/edit/$eqId'
import { Route as OfficeBookingViewBookingIdRouteImport } from './routes/office/booking/view/$bookingId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationIndexRoute = RegistrationIndexRouteImport.update({
  id: '/registration/',
  path: '/registration/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeIndexRoute = OfficeIndexRouteImport.update({
  id: '/office/',
  path: '/office/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookEqIdRoute = BookEqIdRouteImport.update({
  id: '/book/$eqId',
  path: '/book/$eqId',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeConfigurationIndexRoute =
  OfficeConfigurationIndexRouteImport.update({
    id: '/office/configuration/',
    path: '/office/configuration/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFileIndexRoute = ApiFileIndexRouteImport.update({
  id: '/api/file/',
  path: '/api/file/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRegistrationViewIndexRoute =
  OfficeRegistrationViewIndexRouteImport.update({
    id: '/office/registration/view/',
    path: '/office/registration/view/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OfficeRegistrationEditIndexRoute =
  OfficeRegistrationEditIndexRouteImport.update({
    id: '/office/registration/edit/',
    path: '/office/registration/edit/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OfficeEquipmentEditIndexRoute =
  OfficeEquipmentEditIndexRouteImport.update({
    id: '/office/equipment/edit/',
    path: '/office/equipment/edit/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OfficeBookingViewIndexRoute = OfficeBookingViewIndexRouteImport.update({
  id: '/office/booking/view/',
  path: '/office/booking/view/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRegistrationViewRegIdRoute =
  OfficeRegistrationViewRegIdRouteImport.update({
    id: '/office/registration/view/$regId',
    path: '/office/registration/view/$regId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OfficeEquipmentEditEqIdRoute = OfficeEquipmentEditEqIdRouteImport.update({
  id: '/office/equipment/edit/$eqId',
  path: '/office/equipment/edit/$eqId',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeBookingViewBookingIdRoute =
  OfficeBookingViewBookingIdRouteImport.update({
    id: '/office/booking/view/$bookingId',
    path: '/office/booking/view/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/reset-password': typeof ResetPasswordRoute
  '/book/$eqId': typeof BookEqIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/book': typeof BookIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/office': typeof OfficeIndexRoute
  '/registration': typeof RegistrationIndexRoute
  '/api/file': typeof ApiFileIndexRoute
  '/office/configuration': typeof OfficeConfigurationIndexRoute
  '/office/booking/view/$bookingId': typeof OfficeBookingViewBookingIdRoute
  '/office/equipment/edit/$eqId': typeof OfficeEquipmentEditEqIdRoute
  '/office/registration/view/$regId': typeof OfficeRegistrationViewRegIdRoute
  '/office/booking/view': typeof OfficeBookingViewIndexRoute
  '/office/equipment/edit': typeof OfficeEquipmentEditIndexRoute
  '/office/registration/edit': typeof OfficeRegistrationEditIndexRoute
  '/office/registration/view': typeof OfficeRegistrationViewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/reset-password': typeof ResetPasswordRoute
  '/book/$eqId': typeof BookEqIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/book': typeof BookIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/office': typeof OfficeIndexRoute
  '/registration': typeof RegistrationIndexRoute
  '/api/file': typeof ApiFileIndexRoute
  '/office/configuration': typeof OfficeConfigurationIndexRoute
  '/office/booking/view/$bookingId': typeof OfficeBookingViewBookingIdRoute
  '/office/equipment/edit/$eqId': typeof OfficeEquipmentEditEqIdRoute
  '/office/registration/view/$regId': typeof OfficeRegistrationViewRegIdRoute
  '/office/booking/view': typeof OfficeBookingViewIndexRoute
  '/office/equipment/edit': typeof OfficeEquipmentEditIndexRoute
  '/office/registration/edit': typeof OfficeRegistrationEditIndexRoute
  '/office/registration/view': typeof OfficeRegistrationViewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/reset-password': typeof ResetPasswordRoute
  '/book/$eqId': typeof BookEqIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/book/': typeof BookIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/office/': typeof OfficeIndexRoute
  '/registration/': typeof RegistrationIndexRoute
  '/api/file/': typeof ApiFileIndexRoute
  '/office/configuration/': typeof OfficeConfigurationIndexRoute
  '/office/booking/view/$bookingId': typeof OfficeBookingViewBookingIdRoute
  '/office/equipment/edit/$eqId': typeof OfficeEquipmentEditEqIdRoute
  '/office/registration/view/$regId': typeof OfficeRegistrationViewRegIdRoute
  '/office/booking/view/': typeof OfficeBookingViewIndexRoute
  '/office/equipment/edit/': typeof OfficeEquipmentEditIndexRoute
  '/office/registration/edit/': typeof OfficeRegistrationEditIndexRoute
  '/office/registration/view/': typeof OfficeRegistrationViewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot'
    | '/reset-password'
    | '/book/$eqId'
    | '/bookings/$bookingId'
    | '/book'
    | '/bookings'
    | '/office'
    | '/registration'
    | '/api/file'
    | '/office/configuration'
    | '/office/booking/view/$bookingId'
    | '/office/equipment/edit/$eqId'
    | '/office/registration/view/$regId'
    | '/office/booking/view'
    | '/office/equipment/edit'
    | '/office/registration/edit'
    | '/office/registration/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/reset-password'
    | '/book/$eqId'
    | '/bookings/$bookingId'
    | '/book'
    | '/bookings'
    | '/office'
    | '/registration'
    | '/api/file'
    | '/office/configuration'
    | '/office/booking/view/$bookingId'
    | '/office/equipment/edit/$eqId'
    | '/office/registration/view/$regId'
    | '/office/booking/view'
    | '/office/equipment/edit'
    | '/office/registration/edit'
    | '/office/registration/view'
  id:
    | '__root__'
    | '/'
    | '/forgot'
    | '/reset-password'
    | '/book/$eqId'
    | '/bookings/$bookingId'
    | '/book/'
    | '/bookings/'
    | '/office/'
    | '/registration/'
    | '/api/file/'
    | '/office/configuration/'
    | '/office/booking/view/$bookingId'
    | '/office/equipment/edit/$eqId'
    | '/office/registration/view/$regId'
    | '/office/booking/view/'
    | '/office/equipment/edit/'
    | '/office/registration/edit/'
    | '/office/registration/view/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotRoute: typeof ForgotRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  BookEqIdRoute: typeof BookEqIdRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  BookIndexRoute: typeof BookIndexRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  OfficeIndexRoute: typeof OfficeIndexRoute
  RegistrationIndexRoute: typeof RegistrationIndexRoute
  ApiFileIndexRoute: typeof ApiFileIndexRoute
  OfficeConfigurationIndexRoute: typeof OfficeConfigurationIndexRoute
  OfficeBookingViewBookingIdRoute: typeof OfficeBookingViewBookingIdRoute
  OfficeEquipmentEditEqIdRoute: typeof OfficeEquipmentEditEqIdRoute
  OfficeRegistrationViewRegIdRoute: typeof OfficeRegistrationViewRegIdRoute
  OfficeBookingViewIndexRoute: typeof OfficeBookingViewIndexRoute
  OfficeEquipmentEditIndexRoute: typeof OfficeEquipmentEditIndexRoute
  OfficeRegistrationEditIndexRoute: typeof OfficeRegistrationEditIndexRoute
  OfficeRegistrationViewIndexRoute: typeof OfficeRegistrationViewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/': {
      id: '/registration/'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/': {
      id: '/office/'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$eqId': {
      id: '/book/$eqId'
      path: '/book/$eqId'
      fullPath: '/book/$eqId'
      preLoaderRoute: typeof BookEqIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/configuration/': {
      id: '/office/configuration/'
      path: '/office/configuration'
      fullPath: '/office/configuration'
      preLoaderRoute: typeof OfficeConfigurationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file/': {
      id: '/api/file/'
      path: '/api/file'
      fullPath: '/api/file'
      preLoaderRoute: typeof ApiFileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/registration/view/': {
      id: '/office/registration/view/'
      path: '/office/registration/view'
      fullPath: '/office/registration/view'
      preLoaderRoute: typeof OfficeRegistrationViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/registration/edit/': {
      id: '/office/registration/edit/'
      path: '/office/registration/edit'
      fullPath: '/office/registration/edit'
      preLoaderRoute: typeof OfficeRegistrationEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/equipment/edit/': {
      id: '/office/equipment/edit/'
      path: '/office/equipment/edit'
      fullPath: '/office/equipment/edit'
      preLoaderRoute: typeof OfficeEquipmentEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/booking/view/': {
      id: '/office/booking/view/'
      path: '/office/booking/view'
      fullPath: '/office/booking/view'
      preLoaderRoute: typeof OfficeBookingViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/registration/view/$regId': {
      id: '/office/registration/view/$regId'
      path: '/office/registration/view/$regId'
      fullPath: '/office/registration/view/$regId'
      preLoaderRoute: typeof OfficeRegistrationViewRegIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/equipment/edit/$eqId': {
      id: '/office/equipment/edit/$eqId'
      path: '/office/equipment/edit/$eqId'
      fullPath: '/office/equipment/edit/$eqId'
      preLoaderRoute: typeof OfficeEquipmentEditEqIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/booking/view/$bookingId': {
      id: '/office/booking/view/$bookingId'
      path: '/office/booking/view/$bookingId'
      fullPath: '/office/booking/view/$bookingId'
      preLoaderRoute: typeof OfficeBookingViewBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotRoute: ForgotRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  BookEqIdRoute: BookEqIdRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  BookIndexRoute: BookIndexRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  OfficeIndexRoute: OfficeIndexRoute,
  RegistrationIndexRoute: RegistrationIndexRoute,
  ApiFileIndexRoute: ApiFileIndexRoute,
  OfficeConfigurationIndexRoute: OfficeConfigurationIndexRoute,
  OfficeBookingViewBookingIdRoute: OfficeBookingViewBookingIdRoute,
  OfficeEquipmentEditEqIdRoute: OfficeEquipmentEditEqIdRoute,
  OfficeRegistrationViewRegIdRoute: OfficeRegistrationViewRegIdRoute,
  OfficeBookingViewIndexRoute: OfficeBookingViewIndexRoute,
  OfficeEquipmentEditIndexRoute: OfficeEquipmentEditIndexRoute,
  OfficeRegistrationEditIndexRoute: OfficeRegistrationEditIndexRoute,
  OfficeRegistrationViewIndexRoute: OfficeRegistrationViewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
