/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistrationIndexRouteImport } from './routes/registration/index'
import { Route as OfficeIndexRouteImport } from './routes/office/index'
import { Route as ApiFileRouteImport } from './routes/api/file'
import { Route as OfficeRegistrationViewIndexRouteImport } from './routes/office/registration/view/index'
import { Route as OfficeRegistrationEditIndexRouteImport } from './routes/office/registration/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationIndexRoute = RegistrationIndexRouteImport.update({
  id: '/registration/',
  path: '/registration/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeIndexRoute = OfficeIndexRouteImport.update({
  id: '/office/',
  path: '/office/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileRoute = ApiFileRouteImport.update({
  id: '/api/file',
  path: '/api/file',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRegistrationViewIndexRoute =
  OfficeRegistrationViewIndexRouteImport.update({
    id: '/office/registration/view/',
    path: '/office/registration/view/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OfficeRegistrationEditIndexRoute =
  OfficeRegistrationEditIndexRouteImport.update({
    id: '/office/registration/edit/',
    path: '/office/registration/edit/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/file': typeof ApiFileRoute
  '/office': typeof OfficeIndexRoute
  '/registration': typeof RegistrationIndexRoute
  '/office/registration/edit': typeof OfficeRegistrationEditIndexRoute
  '/office/registration/view': typeof OfficeRegistrationViewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/file': typeof ApiFileRoute
  '/office': typeof OfficeIndexRoute
  '/registration': typeof RegistrationIndexRoute
  '/office/registration/edit': typeof OfficeRegistrationEditIndexRoute
  '/office/registration/view': typeof OfficeRegistrationViewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/file': typeof ApiFileRoute
  '/office/': typeof OfficeIndexRoute
  '/registration/': typeof RegistrationIndexRoute
  '/office/registration/edit/': typeof OfficeRegistrationEditIndexRoute
  '/office/registration/view/': typeof OfficeRegistrationViewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/file'
    | '/office'
    | '/registration'
    | '/office/registration/edit'
    | '/office/registration/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/file'
    | '/office'
    | '/registration'
    | '/office/registration/edit'
    | '/office/registration/view'
  id:
    | '__root__'
    | '/'
    | '/api/file'
    | '/office/'
    | '/registration/'
    | '/office/registration/edit/'
    | '/office/registration/view/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiFileRoute: typeof ApiFileRoute
  OfficeIndexRoute: typeof OfficeIndexRoute
  RegistrationIndexRoute: typeof RegistrationIndexRoute
  OfficeRegistrationEditIndexRoute: typeof OfficeRegistrationEditIndexRoute
  OfficeRegistrationViewIndexRoute: typeof OfficeRegistrationViewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/': {
      id: '/registration/'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/': {
      id: '/office/'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file': {
      id: '/api/file'
      path: '/api/file'
      fullPath: '/api/file'
      preLoaderRoute: typeof ApiFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/registration/view/': {
      id: '/office/registration/view/'
      path: '/office/registration/view'
      fullPath: '/office/registration/view'
      preLoaderRoute: typeof OfficeRegistrationViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/registration/edit/': {
      id: '/office/registration/edit/'
      path: '/office/registration/edit'
      fullPath: '/office/registration/edit'
      preLoaderRoute: typeof OfficeRegistrationEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiFileRoute: ApiFileRoute,
  OfficeIndexRoute: OfficeIndexRoute,
  RegistrationIndexRoute: RegistrationIndexRoute,
  OfficeRegistrationEditIndexRoute: OfficeRegistrationEditIndexRoute,
  OfficeRegistrationViewIndexRoute: OfficeRegistrationViewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
